### ISSUE TITLE
Creation of dynamic property PHP 8.2 PHP Deprecated

### ISSUE THREAD

**Issue by ipajen** [palasthotel/wp-cron-logger#4]
please update to remove the warnings. Thank you!

`PHP Deprecated:  Creation of dynamic property CronLogger\Plugin::$path is deprecated in /plugins/cron-logger/classes/Components/Plugin.php on line 27

PHP Deprecated:  Creation of dynamic property CronLogger\Plugin::$url is deprecated in /plugins/cron-logger/classes/Components/Plugin.php on line 28

PHP Deprecated:  Creation of dynamic property CronLogger\Plugin::$basename is deprecated in /plugins/cron-logger/classes/Components/Plugin.php on line 29

PHP Deprecated:  Creation of dynamic property CronLogger\Plugin::$timer is deprecated in /plugins/cron-logger/plugin.php on line 56

PHP Deprecated:  Creation of dynamic property CronLogger\Log::$wpdb is deprecated in /plugins/cron-logger/classes/Log.php on line 20

PHP Deprecated:  Creation of dynamic property CronLogger\Log::$table is deprecated in /plugins/cron-logger/classes/Log.php on line 21

PHP Deprecated:  Creation of dynamic property CronLogger\Plugin::$log is deprecated in /plugins/cron-logger/plugin.php on line 57

PHP Deprecated:  Creation of dynamic property CronLogger\Updates::$plugin is deprecated in /plugins/cron-logger/classes/Updates.php on line 13

PHP Deprecated:  Creation of dynamic property CronLogger\Plugin::$updates is deprecated in /plugins/cron-logger/plugin.php on line 58

PHP Deprecated:  Creation of dynamic property CronLogger\Services\WPCron::$log is deprecated in /plugins/cron-logger/classes/Services/WPCron.php on line 14

PHP Deprecated:  Creation of dynamic property CronLogger\Services\WPCron::$timer is deprecated in /plugins/cron-logger/classes/Services/WPCron.php on line 15

PHP Deprecated:  Creation of dynamic property CronLogger\Services::$wp_cron is deprecated in /plugins/cron-logger/classes/Services.php on line 16

PHP Deprecated:  Creation of dynamic property CronLogger\Services\SolrPlugin::$plugin is deprecated in /plugins/cron-logger/classes/Services/SolrPlugin.php on line 10

PHP Deprecated:  Creation of dynamic property CronLogger\Services::$solr is deprecated in /plugins/cron-logger/classes/Services.php on line 17

PHP Deprecated:  Creation of dynamic property CronLogger\Plugin::$services is deprecated in /plugins/cron-logger/plugin.php on line 59

PHP Deprecated:  Creation of dynamic property CronLogger\Page::$plugin is deprecated in /plugins/cron-logger/classes/Page.php on line 21

PHP Deprecated:  Creation of dynamic property CronLogger\Plugin::$page is deprecated in /plugins/cron-logger/plugin.php on line 60`

**Comment by gosixl** [comment]
+1 - it creates 10,000s lines of logs per day for my site

**Comment by EdwardBock** [comment]
This should be fixed with version 1.2.2
